  services:
    server:
      container_name: server1
      image: server1
      build:
        context: .
        dockerfile: DockerFile
      volumes:
        - /node_modules
      ports:
        - 4001:4001
